---

- name: Record guest ip for orchestration
  lineinfile:
    path: /vagrant/tmp/cluster_nodes
    create: yes
    line: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: Ensure dependencies are installed.
  apt:
    name: software-properties-common
    state: present

- name: Add glusterfs repository
  apt_repository:
    repo: ppa:gluster/glusterfs-3.8
    state: present

- name: Ensure glusterfs is installed.
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - glusterfs-server
    - glusterfs-client

- name: Ensure glusterfs is started and enabled at boot.
  service:
    name: glusterfs-server
    state: started
    enabled: yes

- name: Creates glusterfs mount directory
  file: path=/mnt/glusterfs state=directory

- name: check node count
  shell: wc -l < /vagrant/tmp/cluster_nodes
  register: node_count

- name: Check peer status
  shell: gluster peer status
  register: gluster_peer_status

- name: Initialize glusterfs replicas
  shell: |
    cmd="gluster volume create glfs01 replica {{preferred_node_count}} transport tcp "
    while read node; do
        cmd+=" ${node}:/brick"
        if [$node != '{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}']; then
          eval "gluster peer probe $node"
        fi
    done < /vagrant/tmp/cluster_nodes
    cmd+=" force"
    eval $cmd
    gluster volume start glfs01
  when: >
    'Number of Peers: 0' in gluster_peer_status.stdout
    and node_count.stdout|int == preferred_node_count|int


    