---
- stat:
    path: /vagrant/tmp/manager_ip
  register: swarm_manager_ip

- stat:
    path: /vagrant/tmp/manager_token
  register: swarm_manager_token

- stat:
    path: /vagrant/tmp/worker_token
  register: swarm_worker_token

- name: Checking Swarm Mode Status
  command: "docker info"
  register: "docker_info"
  changed_when: false

- name: Initialize Swarm manager
  shell: >
    docker swarm init --advertise-addr {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }};
    echo {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} > /vagrant/tmp/manager_ip;
    docker swarm join-token -q manager > /vagrant/tmp/manager_token;
    docker swarm join-token -q worker > /vagrant/tmp/worker_token;
  when: >
    'Swarm: inactive' in docker_info.stdout 
    and swarm_manager_ip.stat.islnk is not defined

- name: Join Swarm
  shell: >
    SWARM_MANAGER_IP=`cat /vagrant/tmp/manager_ip`;
    SWARM_TOKEN=`cat /vagrant/tmp/manager_token`;
    docker swarm join \
      --listen-addr {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2377 \
      --advertise-addr {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} \
      --token=$SWARM_TOKEN $SWARM_MANAGER_IP:2377
  when: >
    'Swarm: inactive' in docker_info.stdout
    and swarm_manager_ip.stat.islnk is defined
    and swarm_manager_token.stat.islnk is defined
  