---

- include_tasks: packages.yml

- sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- group:
    name: docker
    state: present

- user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: yes

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- include_tasks: docker-compose.yml
  when: docker_install_compose
