---

- include_tasks: packages.yml

- sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- group:
    name: docker
    state: present

- user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: yes

- name: create docker systemd override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: add docker systemd override
  copy:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf

- name: add systemd override
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Ensure Docker is started and enabled at boot.
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- include_tasks: docker-compose.yml
  when: docker_install_compose
